-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/form_autosave.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/form_autosave (
  fa_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  fa_data BLOB DEFAULT NULL, fa_timestamp BLOB NOT NULL
);
