-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/form_data.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/form_data (
  fd_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  fd_title BLOB DEFAULT '', fd_form BLOB NOT NULL,
  fd_data CLOB NOT NULL, fd_user INTEGER UNSIGNED NOT NULL,
  fd_timestamp BLOB NOT NULL
);
