-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/form_autosave.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/form_autosave (
  fa_id INT AUTO_INCREMENT NOT NULL,
  fa_data LONGBLOB DEFAULT NULL,
  fa_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(fa_id)
) /*$wgDBTableOptions*/;
