-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/form_data.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/form_data (
  fd_id INT AUTO_INCREMENT NOT NULL,
  fd_title VARBINARY(255) DEFAULT '',
  fd_form VARBINARY(255) NOT NULL,
  fd_data LONGTEXT NOT NULL,
  fd_user INT UNSIGNED NOT NULL,
  fd_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(fd_id)
) /*$wgDBTableOptions*/;
