-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/form_data.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE form_data (
  fd_id SERIAL NOT NULL,
  fd_title TEXT DEFAULT '',
  fd_form TEXT NOT NULL,
  fd_data TEXT NOT NULL,
  fd_user INT NOT NULL,
  fd_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(fd_id)
);
